### ISSUE TITLE
crossrefs.py not working

### ISSUE THREAD

**Issue by derickfay** [andrewning/alfred-workflows-scientific#7]
I think the underlying problem is a server issue at crossrefs.org but for whatever reason I'm no longer getting any results, just an error message that No JSON object could be decoded.

`[2017-01-20 09:51:42][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "crossref.py", line 36, in <module>
    for j in r.json():
  File "Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FF564346-F29D-4386-BCE5-4A04E1A02B12/requests/models.py", line 638, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by andrewning** [comment]
Hmm, yeah their server appears to be down or something.  Hopefully it's just temporarily.  Otherwise, I'll look into other options.

**Comment by soto97** [comment]
Currently, the crossref.py script uses the url http://search.labs.crossref.org/dois for the DOI search. However, according to http://labs.crossref.org the meta search system has "graduated" from the Labs portion of CrossRef. So, perhaps the crossref.py script should use this url: http://search.crossref.org ?

There is API documentation at https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md

Unfortunately, I don't know how to work with JASON or APIs in general, so I am at the end of suggestions for right now.

**Comment by andrewning** [comment]
Yeah, you're right, there is a newer API. I'll have to update.
